version: '3'
services:
  puff:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - /data/puff:/data
    image: bitaur/puff:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
